create table
  public.regles (
    id bigint generated by default as identity,
    created_at timestamp with time zone not null default now(),
    "Quand" text null,
    "Alors" text null,
    "Débit" text null,
    "Crédit" text null,
    constraint regles_pkey primary key (id)
  ) tablespace pg_default;